version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mysql
    volumes:
      - ./data/mysqld:/var/run/mysqld
      - ./data/mysql_data:/var/lib/mysql
    networks:
      - debtors_network
    #restart: always
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '${MYSQL_DATABASE_PORT}:3306'
    expose:
      - ${MYSQL_DATABASE_PORT}
  backend:
    env_file:
      - ./backend/.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile-django
    container_name: backend-django
    expose:
      - ${DJANGO_PORT}
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - ./backend:/app
    networks:
      - debtors_network
    depends_on:
      - db
    #restart: always
  #next-frontend:
  #  env_file:
  #    - ./frontend/.env
  #  build:
  #    context: .
  #    dockerfile: ./docker/Dockerfile-nextjs
  #  container_name: frontend-nextjs
  #  ports:
  #    - "${NEXTJS_PORT}:3002"
  #  volumes:
  #    - ./frontend/nextjs:/usr/src/app
  #  depends_on:
  #    - django-backend
    #restart: on-failure
# Names our volume
networks:
  debtors_network:
    driver: bridge