# Generated by Django 4.2.5 on 2023-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('initial_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legal_status', models.CharField(choices=[('Active', 'Active'), ('In litigation', 'In litigation'), ('Closed', 'Closed')], max_length=50)),
            ],
            options={
                'db_table': 'debtor',
            },
        ),
    ]
