# Generated by Django 4.2.5 on 2023-09-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('initial_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legal_status', models.CharField(choices=[('Active', 'Active'), ('In litigation', 'In litigation'), ('Closed', 'Closed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('On time', 'On time'), ('Late', 'Late'), ('Missed', 'Missed')], max_length=50)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtor')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Closed', 'Closed')], max_length=50)),
                ('assigned_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.worker')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtor')),
            ],
        ),
    ]
