# Generated by Django 4.2.5 on 2023-09-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='initial_debt',
        ),
    ]
