# Generated by Django 4.2.5 on 2023-09-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtors', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Closed', 'Closed')], max_length=50)),
                ('assigned_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.debtor')),
            ],
            options={
                'db_table': 'case',
            },
        ),
    ]
