# Generated by Django 4.2.5 on 2023-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='amortization_period',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='case',
            name='borrowed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='case',
            name='payment_frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
