# Generated by Django 4.2.5 on 2023-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_amortization_period_case_borrowed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50),
        ),
    ]
