# Generated by Django 4.2.5 on 2023-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_create_case_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assigned_worker_id', models.IntegerField()),
                ('assigned_worker_name', models.CharField(max_length=50)),
                ('debtor_id', models.IntegerField()),
                ('debtor_name', models.CharField(max_length=50)),
                ('case_status', models.CharField(max_length=50)),
                ('borrowed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amortization_period', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'case_view',
                'managed': False,
            },
        ),
    ]
