# Generated by Django 4.2.5 on 2023-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
    ]
