FROM python:3.11
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY ./backend/requirements.txt /app/requirements.txt
COPY ./backend/ /app
RUN apt-get update \
  && apt-get -y install gcc \
  && apt-get -y install g++ \
  && apt-get -y install unixodbc unixodbc-dev \
  && apt-get clean

RUN apt-get install -y unixodbc-dev

RUN pip install -r /app/requirements.txt

CMD python manage.py makemigrations && python manage.py migrate && \
    python manage.py test && \
    # python manage.py loaddata */fixtures/*.json && \
    python manage.py runserver 0.0.0.0:8000