# Start with a base image containing Node.js 20
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY frontend/frontend_debtors/package*.json ./

# Install project dependencies
RUN npm install

# Expose the default Next.js development server port
EXPOSE 3000

# Start the development server with auto-reloading
CMD ["npm", "run", "dev"]