import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'
import Header from './(layout)/(header)/header'
import Sidebar from './(layout)/(sidebar)/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <Sidebar />
          <main className='flex flex-col justify-center items-center'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
