# Generated by Django 4.2.5 on 2023-09-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_amortization_period_case_borrowed_amount_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='debtor',
        ),
        migrations.AddField(
            model_name='payment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
    ]
